import { DateRange } from "@/app/types/subscription";
import { Mail, NewsSubscription } from "@prisma/client";

export const adminUserIds = ["user_2pthEoa2M0CuCs0pzdjInOTLwcl"];

export const DEFAULT_NEWS_SOURCES = [
  { value: "apnews.com", label: "Associated Press" },
  { value: "reuters.com", label: "Reuters" },
  { value: "bloomberg.com", label: "Bloomberg" },
  { value: "bbc.com/news", label: "BBC News" },
  { value: "cnn.com", label: "CNN" },
  { value: "nytimes.com", label: "The New York Times" },
  { value: "seekingalpha.com", label: "Seeking Alpha" },
  { value: "theguardian.com", label: "The Guardian" },
  { value: "finance.yahoo.com", label: "Yahoo Finance" },
  { value: "investing.com", label: "Investing.com" },
];

export const languages = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "it", name: "Italian" },
  { code: "pt", name: "Portuguese" },
  { code: "nl", name: "Dutch" },
  { code: "pl", name: "Polish" },
  { code: "ru", name: "Russian" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "zh", name: "Chinese" },
];

export const countries = [
  // { code: "af", name: "Afghanistan" },
  // { code: "sq", name: "Albania" },
  // { code: "dz", name: "Algeria" },
  // { code: "as", name: "America Samoa" },
  // { code: "ad", name: "Andorra" },
  // { code: "ao", name: "Angola" },
  // { code: "ai", name: "Anguilla" },
  // { code: "aq", name: "Antarctica" },
  // { code: "ag", name: "Antigua and Barbuda" },
  { code: "ar", name: "Argentina" },
  // { code: "am", name: "Armenia" },
  // { code: "aw", name: "Aruba" },
  { code: "au", name: "Australia" },
  // { code: "at", name: "Austria" },
  // { code: "az", name: "Azerbaijan" },
  // { code: "bs", name: "Bahamas" },
  // { code: "bh", name: "Bahrain" },
  // { code: "bd", name: "Bangladesh" },
  // { code: "bb", name: "Barbados" },
  // { code: "by", name: "Belarus" },
  // { code: "be", name: "Belgium" },
  // { code: "bz", name: "Belize" },
  // { code: "bj", name: "Benin" },
  // { code: "bt", name: "Bhutan" },
  // { code: "bo", name: "Bolivia" },
  // { code: "ba", name: "Bosnia and Herzegovina" },
  // { code: "bw", name: "Botswana" },
  // { code: "br", name: "Brazil" },
  // { code: "bn", name: "Brunei" },
  // { code: "bg", name: "Bulgaria" },
  // { code: "bf", name: "Burkina Faso" },
  // { code: "bi", name: "Burundi" },
  // { code: "kh", name: "Cambodia" },
  // { code: "cm", name: "Cameroon" },
  // { code: "ca", name: "Canada" },
  // { code: "cv", name: "Cape Verde" },
  // { code: "cf", name: "Central African Republic" },
  // { code: "td", name: "Chad" },
  { code: "cl", name: "Chile" },
  { code: "cn", name: "China" },
  // { code: "co", name: "Colombia" },
  // { code: "km", name: "Comoros" },
  // { code: "cg", name: "Congo" },
  // { code: "cr", name: "Costa Rica" },
  // { code: "hr", name: "Croatia" },
  // { code: "cu", name: "Cuba" },
  // { code: "cy", name: "Cyprus" },
  // { code: "cz", name: "Czech Republic" },
  // { code: "dk", name: "Denmark" },
  // { code: "dj", name: "Djibouti" },
  // { code: "dm", name: "Dominica" },
  // { code: "do", name: "Dominican Republic" },
  // { code: "ec", name: "Ecuador" },
  { code: "eg", name: "Egypt" },
  // { code: "sv", name: "El Salvador" },
  // { code: "gq", name: "Equatorial Guinea" },
  { code: "hk", name: "Hong Kong" },
  // { code: "er", name: "Eritrea" },
  // { code: "ee", name: "Estonia" },
  // { code: "et", name: "Ethiopia" },
  // { code: "fj", name: "Fiji" },
  // { code: "fi", name: "Finland" },
  // { code: "fr", name: "France" },
  // { code: "ga", name: "Gabon" },
  // { code: "gm", name: "Gambia" },
  // { code: "ge", name: "Georgia" },
  { code: "de", name: "Germany" },
  // { code: "gh", name: "Ghana" },
  { code: "gr", name: "Greece" },
  // { code: "gd", name: "Grenada" },
  // { code: "gt", name: "Guatemala" },
  // { code: "gn", name: "Guinea" },
  // { code: "gw", name: "Guinea-Bissau" },
  // { code: "gy", name: "Guyana" },
  // { code: "ht", name: "Haiti" },
  // { code: "hn", name: "Honduras" },
  // { code: "hu", name: "Hungary" },
  { code: "is", name: "Iceland" },
  { code: "in", name: "India" },
  // { code: "id", name: "Indonesia" },
  { code: "ir", name: "Iran" },
  { code: "iq", name: "Iraq" },
  { code: "ie", name: "Ireland" },
  { code: "il", name: "Israel" },
  { code: "it", name: "Italy" },
  { code: "jm", name: "Jamaica" },
  { code: "jp", name: "Japan" },
  { code: "jo", name: "Jordan" },
  // { code: "kz", name: "Kazakhstan" },
  // { code: "ke", name: "Kenya" },
  // { code: "ki", name: "Kiribati" },
  { code: "kp", name: "North Korea" },
  { code: "kr", name: "South Korea" },
  // { code: "kw", name: "Kuwait" },
  // { code: "kg", name: "Kyrgyzstan" },
  // { code: "la", name: "Laos" },
  // { code: "lv", name: "Latvia" },
  // { code: "lb", name: "Lebanon" },
  // { code: "ls", name: "Lesotho" },
  // { code: "lr", name: "Liberia" },
  // { code: "ly", name: "Libya" },
  // { code: "li", name: "Liechtenstein" },
  // { code: "lt", name: "Lithuania" },
  // { code: "lu", name: "Luxembourg" },
  // { code: "mk", name: "North Macedonia" },
  // { code: "mg", name: "Madagascar" },
  // { code: "mw", name: "Malawi" },
  { code: "my", name: "Malaysia" },
  // { code: "mv", name: "Maldives" },
  // { code: "ml", name: "Mali" },
  // { code: "mt", name: "Malta" },
  // { code: "mh", name: "Marshall Islands" },
  // { code: "mr", name: "Mauritania" },
  // { code: "mu", name: "Mauritius" },
  { code: "mx", name: "Mexico" },
  // { code: "fm", name: "Micronesia" },
  // { code: "md", name: "Moldova" },
  // { code: "mc", name: "Monaco" },
  // { code: "mn", name: "Mongolia" },
  // { code: "me", name: "Montenegro" },
  // { code: "ma", name: "Morocco" },
  // { code: "mz", name: "Mozambique" },
  { code: "mm", name: "Myanmar" },
  // { code: "na", name: "Namibia" },
  // { code: "nr", name: "Nauru" },
  // { code: "np", name: "Nepal" },
  // { code: "nl", name: "Netherlands" },
  { code: "nz", name: "New Zealand" },
  // { code: "ni", name: "Nicaragua" },
  // { code: "ne", name: "Niger" },
  // { code: "ng", name: "Nigeria" },
  // { code: "no", name: "Norway" },
  // { code: "om", name: "Oman" },
  // { code: "pk", name: "Pakistan" },
  // { code: "pw", name: "Palau" },
  // { code: "pa", name: "Panama" },
  // { code: "pg", name: "Papua New Guinea" },
  // { code: "py", name: "Paraguay" },
  // { code: "pe", name: "Peru" },
  { code: "ph", name: "Philippines" },
  { code: "pl", name: "Poland" },
  { code: "pt", name: "Portugal" },
  { code: "qa", name: "Qatar" },
  // { code: "ro", name: "Romania" },
  { code: "ru", name: "Russia" },
  // { code: "rw", name: "Rwanda" },
  // { code: "lc", name: "Saint Lucia" },
  // { code: "vc", name: "Saint Vincent and the Grenadines" },
  // { code: "ws", name: "Samoa" },
  // { code: "st", name: "Sao Tome and Principe" },
  { code: "sa", name: "Saudi Arabia" },
  // { code: "sn", name: "Senegal" },
  // { code: "rs", name: "Serbia" },
  // { code: "sc", name: "Seychelles" },
  // { code: "sl", name: "Sierra Leone" },
  // { code: "sg", name: "Singapore" },
  // { code: "sk", name: "Slovakia" },
  // { code: "si", name: "Slovenia" },
  // { code: "sb", name: "Solomon Islands" },
  // { code: "so", name: "Somalia" },
  { code: "za", name: "South Africa" },
  { code: "ss", name: "South Sudan" },
  { code: "es", name: "Spain" },
  { code: "lk", name: "Sri Lanka" },
  { code: "sd", name: "Sudan" },
  // { code: "sr", name: "Suriname" },
  { code: "se", name: "Sweden" },
  { code: "ch", name: "Switzerland" },
  // { code: "sy", name: "Syria" },
  // { code: "tw", name: "Taiwan" },
  // { code: "tj", name: "Tajikistan" },
  // { code: "tz", name: "Tanzania" },
  // { code: "th", name: "Thailand" },
  // { code: "tg", name: "Togo" },
  // { code: "to", name: "Tonga" },
  // { code: "tt", name: "Trinidad and Tobago" },
  // { code: "tn", name: "Tunisia" },
  { code: "tr", name: "Turkey" },
  // { code: "tm", name: "Turkmenistan" },
  // { code: "tv", name: "Tuvalu" },
  // { code: "ug", name: "Uganda" },
  { code: "ua", name: "Ukraine" },
  // { code: "ae", name: "United Arab Emirates" },
  { code: "gb", name: "United Kingdom" },
  { code: "us", name: "United States" },
  // { code: "uy", name: "Uruguay" },
  // { code: "uz", name: "Uzbekistan" },
  // { code: "vu", name: "Vanuatu" },
  // { code: "va", name: "Vatican City" },
  // { code: "ve", name: "Venezuela" },
  { code: "vn", name: "Vietnam" },
  // { code: "ye", name: "Yemen" },
  // { code: "zm", name: "Zambia" },
  // { code: "zw", name: "Zimbabwe" },
];

export const SerperDateRangeInputMap: Record<DateRange, string | undefined> = {
  any_time: undefined,
  past_hour: "qdr:h",
  past_24_hours: "qdr:d",
  past_week: "qdr:w",
  past_month: "qdr:m",
  past_year: "qdr:y",
};

export const promptIcons = [
  "📝",
  "📰",
  "💼",
  "⏱️",
  "🌐",
  "💬",
  "⚖️",
  "📈",
  "💰",
  "📊",
  "🔗",
  "🗺️",
  "🌡️",
  "📢",
  "🌟",
  "👥",
  "🔍",
  "🔮",
  "💭",
  "💡",
  "🚀",
  "💥",
  "🏛️",
  "✅",
  "⚠️",
  "🤔",
  "📰✨",
  "🧲",
  "🔔",
  "🗃️",
  "🔎",
  "🧭",
  "💯",
  "🚫",
  "🧒",
  "📖",
  "📚",
  "✍️",
  "🎓",
  "🏠📈",
];

export const categories = [
  // Core News Understanding & Analysis
  "News Summarization",
  "Event Extraction",
  "Timeline Generation",
  "Topic Clustering",
  "Named Entity Recognition",
  "Relationship Extraction",
  "Sentiment Analysis",
  "News Comparison",
  "Trend Analysis",

  // Source & Information Credibility
  "Bias Detection",
  "Credibility Assessment",
  "Fact Checking",
  "Misinformation Detection",
  "Propaganda Detection",

  // Multi-Document & Cross-Lingual Processing
  "Multi-Document Summarization",
  "Cross-Lingual News Analysis",
  "News Translation",

  // User-Centric Features & Personalization
  "Question Answering",
  "Personalized News Digest",
  "Content Recommendation",
  "News Alerting",

  // Advanced & Creative Applications
  "News-Based Story Generation",
  "Data Visualization from News",
  "Predictive Analytics from News",
  "Automated News Reporting",

  "News Analysis",
  "Financial Insights",
  "Sentiment Analysis",
  "Risk Assessment",
  "Personalized News",
  "Simplified Explanation",
  "Personalized Learning",
  "Property Analysis",
  "Brand Reputation Monitoring",
];

export const promptCategories = [
  "News Analysis",
  "Financial Insights",
  "Market Context",
  "Sentiment Analysis",
  "Strategic Forecasting",
  "Risk Assessment",
  "Personalized News",
  "Credibility Assessment",
  "Simplified Explanation",
  "Creative Applications",
  "Personalized Learning",
  "Property Analysis",
  "Brand Reputation Monitoring",
  "Other",
];

export const builtInPrompts = [
  {
    id: "1",
    title: "Key Takeaways",
    description:
      "Extract the 5 most important takeaways about {keywords} from these news, focusing on actionable insights.",
    category: "News Analysis",
    icon: "📰",
  },
  {
    id: "2",
    title: "Executive Summary",
    description:
      "Create a concise summary of the key developments and their implications, suitable for a busy executive.",
    category: "News Analysis",
    app: "Summarizer",
    icon: "💼",
  },
  {
    id: "3",
    title: "Bullet Point Breakdown",
    description:
      "Present the essential facts and figures from these news in a clear and scannable bullet-point format.",
    category: "News Analysis",
    app: "Summarizer",
    icon: "•",
  },
  {
    id: "4",
    title: "Timeline of Events",
    description:
      "Construct a chronological timeline of the key events related to {keywords} mentioned in the news.",
    category: "News Analysis",
    app: "Timeline Generator",
    icon: "⏱️",
  },
  {
    id: "5",
    title: "Multi-Article Synthesis",
    description:
      "Combine information from multiple news to provide a comprehensive overview of the situation surrounding {keywords}.",
    category: "News Analysis",
    app: "Synthesizer",
    icon: "🌐",
  },
  {
    id: "6",
    title: "Expert Opinions",
    description:
      "What do analysts and experts say about {subscription_name}'s future based on this news? Extract and summarize their opinions.",
    category: "Financial Insights",
    app: "Quote Extractor",
    icon: "💬",
  },
  {
    id: "7",
    title: "Bull vs. Bear Case",
    description:
      "Present the strongest arguments FOR and AGAINST {subscription_name}'s success based on the evidence in these articles.",
    category: "Financial Insights",
    app: "Argument Builder",
    icon: "⚖️",
  },
  {
    id: "8",
    title: "Investment Thesis Builder",
    description:
      "Based on the news analysis, construct a concise investment thesis for or against {keywords}, including supporting arguments and potential risks.",
    category: "Financial Insights",
    app: "Thesis Generator",
    icon: "📈",
  },
  {
    id: "9",
    title: "Financial Health Checkup",
    description:
      "Analyze the latest financial data and news about {keywords} to assess their current financial health and future prospects.",
    category: "Financial Insights",
    app: "Financial Analyzer",
    icon: "💰",
  },
  {
    id: "10",
    title: "Valuation Analysis",
    description:
      "Based on the information available, how does {keywords}'s current valuation compare to its peers and historical performance?",
    category: "Financial Insights",
    app: "Valuation Tool",
    icon: "📊",
  },
  {
    id: "11",
    title: "Related Developments",
    description:
      "Identify other companies, industries, or markets impacted by the news about {keywords} and explain the connections.",
    category: "Market Context",
    app: "Connection Finder",
    icon: "🔗",
  },
  {
    id: "12",
    title: "Competitor Comparison",
    description:
      "Analyze how the news about {keywords} positions them against their main competitors. Identify potential advantages or disadvantages.",
    category: "Market Context",
    app: "Competitor Matrix",
    icon: "🆚",
  },
  {
    id: "13",
    title: "Industry Trend Analysis",
    description:
      "Extract insights from the news to identify emerging trends and potential disruptions within {keywords}'s industry.",
    category: "Market Context",
    app: "Trend Analyzer",
    icon: "📈",
  },
  {
    id: "14",
    title: "Market Share Implications",
    description:
      "How might the news about {keywords} impact their market share and competitive landscape in the short and long term?",
    category: "Market Context",
    app: "Market Simulator",
    icon: "🗺️",
  },
  {
    id: "15",
    title: "SWOT Analysis",
    description:
      "Conduct a SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) for {keywords} based on the information presented in the news.",
    category: "Market Context",
    app: "SWOT Analyzer",
    icon: " SWOT",
  },
  {
    id: "16",
    title: "Sentiment Shift",
    description:
      "Has the overall sentiment towards {keywords} become more positive or negative based on recent news? Provide evidence.",
    category: "Sentiment Analysis",
    app: "Sentiment Gauge",
    icon: "🌡️",
  },
  {
    id: "17",
    title: "Public Perception Tracker",
    description:
      "Analyze social media and online discussions to understand how the public's perception of {keywords} is changing in light of recent news.",
    category: "Sentiment Analysis",
    app: "Perception Analyzer",
    icon: "📢",
  },
  {
    id: "18",
    title: "Reputation Management",
    description:
      "Identify any potential reputational risks or opportunities for {keywords} based on the public's reaction to the news.",
    category: "Sentiment Analysis",
    app: "Reputation Manager",
    icon: "🌟",
  },
  {
    id: "19",
    title: "Key Stakeholder Sentiment",
    description:
      "Analyze the sentiment expressed by specific stakeholder groups (e.g., customers, employees, investors) towards {keywords}.",
    category: "Sentiment Analysis",
    app: "Stakeholder Sentiment Analyzer",
    icon: "👥",
  },
  {
    id: "20",
    title: "Sentiment Drivers",
    description:
      "What are the main factors driving positive or negative sentiment towards {keywords} according to the news and public opinion?",
    category: "Sentiment Analysis",
    app: "Sentiment Driver Analyzer",
    icon: "🔍",
  },
  {
    id: "21",
    title: "Future Implications",
    description:
      "Extrapolate from the current news to identify potential long-term consequences and trends for {keywords} and its industry.",
    category: "Strategic Forecasting",
    app: "Futurecasting Tool",
    icon: "🔮",
  },
  {
    id: "22",
    title: "Scenario Planning",
    description:
      "Develop multiple plausible future scenarios for {keywords} based on different interpretations of the news and potential events.",
    category: "Strategic Forecasting",
    app: "Scenario Planner",
    icon: "💭",
  },
  {
    id: "23",
    title: "Strategic Recommendations",
    description:
      "Based on the news analysis and future outlook, provide actionable strategic recommendations for {keywords}.",
    category: "Strategic Forecasting",
    app: "Recommendation Engine",
    icon: "💡",
  },
  {
    id: "24",
    title: "Innovation Opportunities",
    description:
      "Identify potential areas where {keywords} could innovate or adapt their business model in response to the evolving landscape.",
    category: "Strategic Forecasting",
    app: "Innovation Finder",
    icon: "🚀",
  },
  {
    id: "25",
    title: "Disruption Potential",
    description:
      "Assess the likelihood of the news about {keywords} leading to significant disruption or transformation within their industry.",
    category: "Strategic Forecasting",
    app: "Disruption Analyzer",
    icon: "💥",
  },
  {
    id: "26",
    title: "Regulatory Landscape",
    description:
      "Identify any potential legal, regulatory, or political implications arising from the news about {keywords}.",
    category: "Risk Assessment",
    app: "Policy Analyzer",
    icon: "🏛️",
  },
  {
    id: "27",
    title: "Compliance Monitoring",
    description:
      "Analyze the news for any potential compliance issues or regulatory risks that {keywords} should be aware of.",
    category: "Risk Assessment",
    app: "Compliance Tracker",
    icon: "✅",
  },
  {
    id: "28",
    title: "Litigation Risk",
    description:
      "Assess the likelihood of the news about {keywords} leading to legal challenges or lawsuits from competitors, customers, or other parties.",
    category: "Risk Assessment",
    app: "Litigation Forecaster",
    icon: "⚠️",
  },
  {
    id: "29",
    title: "Reputational Risk",
    description:
      "Identify any potential reputational risks or damage that {keywords} might face as a result of the news.",
    category: "Risk Assessment",
    app: "Reputation Monitor",
    icon: "💔",
  },
  {
    id: "30",
    title: "Ethical Considerations",
    description:
      "Analyze the news for any ethical dilemmas or controversies that {keywords} might need to address.",
    category: "Risk Assessment",
    app: "Ethics Analyzer",
    icon: "🤔",
  },
  {
    id: "31",
    title: "Personalized News Digest",
    description:
      "Create a concise summary of the most relevant news about {keywords} tailored to my specific interests (e.g., financial performance, technological advancements, environmental impact).",
    category: "Personalized News",
    app: "News Digest Creator",
    icon: "📰✨",
  },
  {
    id: "32",
    title: "Content Recommendation Engine",
    description:
      "Based on my reading history and preferences, recommend other relevant articles, reports, or analyses related to {keywords}.",
    category: "Personalized News",
    app: "Content Recommender",
    icon: "🧲",
  },
  {
    id: "33",
    title: "News Alert System",
    description:
      "Set up customized alerts to notify me of any breaking news or significant developments related to {keywords}.",
    category: "Personalized News",
    app: "Alert Creator",
    icon: "🔔",
  },
  {
    id: "34",
    title: "Topic Clustering",
    description:
      "Group related news articles about {keywords} into meaningful clusters based on their content and themes.",
    category: "Personalized News",
    app: "Topic Clusterer",
    icon: "🗃️",
  },
  {
    id: "35",
    title: "Content Summarization by Language",
    description:
      "Summarize the key points of this news about {keywords} in [Target Language].",
    category: "Personalized News",
    app: "Multilingual Summarizer",
    icon: "🌐",
  },
  {
    id: "36",
    title: "Fact Check",
    description:
      "Highlight any claims made about {keywords} that require further verification or scrutiny.",
    category: "Credibility Assessment",
    app: "Fact Checker",
    icon: "🔎",
  },
  {
    id: "37",
    title: "News Source Bias Detection",
    description:
      "Analyze the sources of these news articles and identify any potential biases (political leaning, financial interests, etc.) that might be influencing their reporting.",
    category: "Credibility Assessment",
    app: "Bias Detector",
    icon: "🧭",
  },
  {
    id: "38",
    title: "Source Credibility Assessment",
    description:
      "Evaluate the trustworthiness and reliability of the sources cited in the news articles about {keywords}.",
    category: "Credibility Assessment",
    app: "Credibility Analyzer",
    icon: "💯",
  },
  {
    id: "39",
    title: "Propaganda Detection",
    description:
      "Analyze the language and framing used in the news to identify any potential attempts at manipulation or propaganda.",
    category: "Credibility Assessment",
    app: "Propaganda Detector",
    icon: "⚠️",
  },
  {
    id: "40",
    title: "Misinformation Filtering",
    description:
      "Filter out any potentially false or misleading information from the news about {keywords}.",
    category: "Credibility Assessment",
    app: "Misinformation Filter",
    icon: "🚫",
  },
  {
    id: "41",
    title: "Explain Like I'm 5",
    description:
      "Explain the key points of this news about {keywords} in simple terms that a 5-year-old could understand.",
    category: "Simplified Explanation",
    app: "ELI5 Generator",
    icon: "🧒",
  },
  {
    id: "42",
    title: "Plain Language Summary",
    description:
      "Provide a clear and concise summary of the news about {keywords} using plain language that is easy for anyone to understand.",
    category: "Simplified Explanation",
    app: "Plain Language Summarizer",
    icon: "📖",
  },
  {
    id: "43",
    title: "Key Concepts Glossary",
    description:
      "Create a glossary of key terms and concepts related to {keywords} and the news, explaining them in simple language.",
    category: "Simplified Explanation",
    app: "Glossary Generator",
    icon: "📚",
  },
  {
    id: "44",
    title: "Visual Explainer",
    description:
      "Generate a simple infographic or visual representation of the key information presented in the news about {keywords}.",
    category: "Simplified Explanation",
    app: "Infographic Generator",
    icon: "📊",
  },
  {
    id: "46",
    title: "News-Based Story Generation",
    description:
      "Use the information from the news about {keywords} to create a short story, fictional scenario, or hypothetical dialogue.",
    category: "Creative Applications",
    app: "Story Generator",
    icon: "✍️",
  },
  {
    id: "47",
    title: "Data Visualization & Dashboards",
    description:
      "Generate interactive charts, graphs, and dashboards to visualize the key data and trends extracted from the news about {keywords}.",
    category: "Creative Applications",
    app: "Data Visualization Tool",
    icon: "📈",
  },
  {
    id: "48",
    title: "Predictive Analytics",
    description:
      "Based on historical data and current trends identified in the news, make predictions about the future performance of {keywords}.",
    category: "Creative Applications",
    app: "Predictive Model",
    icon: "🔮",
  },
  {
    id: "49",
    title: "Sentiment-Based Stock Market Simulation",
    description:
      "Simulate how the stock market might react to the news about {keywords} based on the prevailing sentiment and investor behavior.",
    category: "Creative Applications",
    app: "Market Simulator",
    icon: "📈",
  },
  {
    id: "50",
    title: "Personalized Learning Recommendations",
    description:
      "Based on my interest in {keywords} and the news I've read, recommend relevant books, courses, or resources to deepen my understanding.",
    category: "Personalized Learning",
    app: "Learning Recommender",
    icon: "🎓",
  },
  {
    id: "51",
    title: "Property Market Insights",
    description:
      "Analyze news articles and market data to identify trends and factors influencing property prices in {keywords}, including supply and demand dynamics, interest rates, and economic indicators.",
    category: "Property Analysis",
    app: "Real Estate Insights",
    icon: "🏠📈",
  },
];

export const exampleMail: Mail = {
  id: "cm56ta4g50001ufkp1py9czdr",
  createdAt: new Date("2024-12-27T13:51:01.274000"),
  newsSubscriptionId: "cm554j1vv000vkp6uatn2kcnz",
  scrapeContent: ["", ""],
  searchResult: {
    searchParameters: {
      q: "elon musk OR tesla OR tesla fsd OR tesla stock site:finance.yahoo.com OR site:seekingalpha.com",
      gl: "us",
      hl: "en",
      type: "news",
      num: 10,
      tbs: "qdr:d",
      engine: "google",
    },
    news: [
      {
        title:
          "Tesla to Report Delivery Numbers Soon, as Analysts Weigh 2025 Outlook",
        link: "https://finance.yahoo.com/news/tesla-report-delivery-numbers-soon-162811630.html",
        snippet:
          "Despite residual macroeconomic uncertainty, experts predict increase in car deliveries and developments in artificial intelligence and autonomous driving...",
        date: "2024-12-27T00:50:07.661779",
        source: "Yahoo Finance",
        imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo6bfuoRlckFjk_fjbj_d2P28IMIXL0IIT6AyvR98mmZ2wrqXAHYpV3E0&usqp=CAI&s",
        position: 1,
      },
      {
        title: "Elon Musk's Weight-Loss Secret Shakes Up Pharma Giants",
        link: "https://finance.yahoo.com/news/elon-musks-weight-loss-secret-143648523.html",
        snippet:
          "Elon Musk just dropped a weight-loss bombshell. The Tesla (NASDAQ:TSLA) and SpaceX CEO took to social media, revealing he uses Eli Lilly's (NYSE:LLY)...",
        date: "2024-12-26T22:50:07.661818",
        source: "Yahoo Finance",
        imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSK7OK3nqx6Rqe2Bn6NjkrZgIlNtfyYMxwVCTK3K2Q&usqp=CAI&s",
        position: 2,
      },
      {
        title: "",
        link: "https://finance.yahoo.com/m/7ba4c6e9-e00c-3c14-a4f5-caaf8dfbc5b9/is-tesla-stock-a-buy-or-a.html",
        date: "2024-12-27T11:50:07.661829",
        source: "Yahoo Finance",
        imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBa_jqPh4RwEirL_dYRCyVA5JgghuCDJok0ifVJR0qBRtDWakjEJ6Z5g&usqp=CAI&s",
        position: 3,
      },
      {
        title: "Tesla Just Unveiled a New Mezcal\u2014and We Got a Taste",
        link: "https://finance.yahoo.com/news/tesla-just-unveiled-mezcal-got-200000013.html",
        snippet:
          "Elon Musk has been a presence in our lives for a long time now, and it doesn't seem like that's going to change any time soon. Whether it's starting Tesla,...",
        date: "2024-12-27T03:50:07.661836",
        source: "Yahoo Finance",
        imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQH37i99rR8jwuA_Pkj6WcR7w3_CPCOazs0iHi-Ug4-LvxFqTvuIL4zgs&usqp=CAI&s",
        position: 4,
      },
      {
        title:
          "Elon Musk Praises Boeing's Leadership Overhaul, Slams Artemis Moon Missions as 'Inefficient",
        link: "https://finance.yahoo.com/news/elon-musk-praises-boeings-leadership-182842424.html",
        snippet:
          "Musk lauds Boeing's leadership shift, criticizes NASA's Artemis program, and emphasizes innovation in aerospace and beyond.",
        date: "2024-12-27T02:50:07.661844",
        source: "Yahoo Finance",
        imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzyouk61Ssg-6lWvks01ik07GyMNYHaeFbSf4H-A3yXEdkwGDCba9TkA&usqp=CAI&s",
        position: 5,
      },
      {
        title:
          "Elon Musk: Boeing is on \u2018much better track\u2019 with new CEO (NYSE:BA)",
        link: "https://seekingalpha.com/news/4390997-elon-musk-boeing-is-on-much-better-track-with-new-ceo",
        snippet:
          "Financial writer Elon Musk criticizes Boeing's management and NASA's Artemis missions as inefficient, calling for new approaches in aviation and space...",
        date: "2024-12-26T23:50:07.661851",
        source: "Seeking Alpha",
        imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5neRhPei9r-4luWHffNk3WybFNWPW-CeBAO7nVoVZK3bpEZk0W7YHFYs&usqp=CAI&s",
        position: 6,
      },
      {
        title:
          "Elon Musk\u2019s Biggest Fans Turn Against Him Over Immigration",
        link: "https://finance.yahoo.com/news/elon-musk-biggest-fans-turn-135830459.html",
        snippet:
          "In a surprising twist of events, Elon Musk is feuding with the MAGA base.",
        date: "2024-12-26T21:50:07.661858",
        source: "Yahoo Finance",
        imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKJ89ql31B5XDeuxzc5pLoun2P2j70rIBlcgpHq-FhhQawnSg0ESn6QAs&usqp=CAI&s",
        position: 7,
      },
      {
        title: "Elon Musk\u2019s go-to cost-cutter is working for DOGE",
        link: "https://finance.yahoo.com/news/elon-musk-cost-cutter-working-090002891.html",
        snippet:
          "(Bloomberg) -- Elon Musk's deputy Steve Davis has spent more than 20 years helping the billionaire cut costs at businesses like SpaceX, the Boring Company...",
        date: "2024-12-27T10:50:07.661865",
        source: "Yahoo Finance",
        imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdGG9zwTFjREzKLT0u8yWgV7Jd4xIgiRo8ollLYFyoMn7OdFKR6vA8Nb4&usqp=CAI&s",
        position: 8,
      },
      {
        title:
          "Stock market today: Dow ekes out gains, bitcoin slumps as 'Santa Claus' rally takes a pause",
        link: "https://finance.yahoo.com/news/live/stock-market-today-dow-ekes-out-gains-bitcoin-slumps-as-santa-claus-rally-takes-a-pause-175235354.html",
        snippet:
          "US stocks were set to open post-Christmas trading with a bit of a hangover.",
        date: "2024-12-27T04:50:07.661871",
        source: "Yahoo Finance",
        imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6X0hWsK3x9xtUe6VdxzglhWd5JQJckgaMxTjAv4c4cjaI6O8e0sQRtXw&usqp=CAI&s",
        position: 9,
      },
      {
        title:
          "Stock market today: Dow, S&P 500, Nasdaq futures fall after Christmas break",
        link: "https://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-futures-fall-after-christmas-break-140313607.html",
        snippet:
          "US stocks were set to open post-Christmas trading with a bit of a hangover.",
        date: "2024-12-26T21:50:07.661878",
        source: "Yahoo Finance",
        imageUrl:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQG_1maU-tJPLy0g7IJviL7AKuoeb4K2CgKsGndSj0JdpeEkIMpMsMvhrM&usqp=CAI&s",
        position: 10,
      },
    ],
    credits: 1,
  },
  content:
    "### Comprehensive Analysis of Tesla, Elon Musk, and Tesla Stock\n\n#### **1. Key Elements**\nThe provided news articles focus on **Tesla**, **Elon Musk**, **Tesla stock**, and **Tesla's Full Self-Driving (FSD)** technology. Key themes include Tesla's financial performance, industry trends in electric vehicles (EVs) and autonomous driving, market sentiment, and potential risks and opportunities for investors.\n\n---\n\n#### **2. Evaluate Company Performance**\nTesla's financial performance is highlighted by its **delivery numbers** and **growth expectations**. Analysts predict a **6% year-over-year increase** in Q3 2024 deliveries, with **Model 3 and Model Y** accounting for the majority of sales. Tesla aims to exceed **1.8 million vehicles sold** in 2024, with Q4 deliveries expected to surpass **515,000 units**. Analysts like Dan Ives of Wedbush Securities have raised Tesla's price target to **$515**, citing potential benefits from advancements in **artificial intelligence (AI)** and **autonomous driving technology**. Under ideal conditions, Tesla's stock could rise to **$650 by 2025**.\n\n---\n\n#### **3. Assess Industry Trends**\nThe EV and autonomous driving industries are experiencing significant developments. Tesla is seen as a leader in **autonomous technology**, with analysts emphasizing the importance of **customer demand** and **government support** for its expansion. The **Cybertruck** and **Semitruck** production are expected to be key growth drivers in 2025. However, the industry faces challenges, including **regulatory hurdles** and **competitive pressures** from other automakers and tech companies.\n\n---\n\n#### **4. Gauge Market Sentiment**\nMarket sentiment toward Tesla is mixed. On one hand, the stock has surged **80%** since Donald Trump's election win, driven by optimism around **self-driving technology** and a potentially **favorable regulatory environment**. On the other hand, some analysts, like those at Barclays, argue that the rally reflects a **\"sharp disconnect\"** between Tesla's stock price and its fundamentals, comparing it to **cryptocurrencies**. Public perception of Elon Musk also plays a role, with some of his **MAGA supporters** turning against him over **immigration policies**, which could impact Tesla's brand image.\n\n---\n\n#### **5. Identify Buy Signals**\nSeveral buy signals suggest potential upside for Tesla stock:\n- **Positive earnings reports**: Analysts expect strong delivery numbers and revenue growth in 2025.\n- **Favorable industry developments**: Advances in AI and autonomous driving technology could boost Tesla's market position.\n- **Optimistic market sentiment**: The stock's recent rally and high price targets indicate investor confidence.\n\n---\n\n#### **6. Highlight Risks**\nKey risks include:\n- **Regulatory challenges**: Tesla's success in 2025 will depend on its ability to navigate legal and regulatory environments.\n- **Competitive threats**: Other automakers and tech companies are investing heavily in EVs and autonomous driving.\n- **Negative sentiment**: Elon Musk's controversies and potential backlash from his political stances could harm Tesla's brand.\n\n---\n\n#### **7. Provide Actionable Insights**\nBased on the analysis, Tesla stock presents a **potential buying opportunity** for investors with a high-risk tolerance. The company's leadership in EV and autonomous driving technology, combined with strong growth expectations, makes it an attractive long-term investment. However, investors should be cautious of **regulatory risks**, **competitive pressures**, and **market volatility**.\n\n---\n\n#### **8. Step-by-Step Summary**\n| **Positive Indicators**                     | **Negative Indicators**                     |\n|---------------------------------------------|---------------------------------------------|\n| Strong delivery numbers and revenue growth  | Regulatory challenges                       |\n| Leadership in autonomous driving technology | Competitive threats from other automakers   |\n| Optimistic market sentiment and high targets| Negative sentiment around Elon Musk         |\n| Favorable industry trends                   | Market volatility and speculative trading   |\n\n**Conclusion**: Tesla stock offers significant growth potential, but investors should carefully weigh the risks and opportunities before making a decision.\n\n---\n\n**Reference Links**:\nhttps://finance.yahoo.com/news/tesla-report-delivery-numbers-soon-162811630.html  \nhttps://finance.yahoo.com/news/elon-musks-weight-loss-secret-143648523.html  \nhttps://finance.yahoo.com/m/7ba4c6e9-e00c-3c14-a4f5-caaf8dfbc5b9/is-tesla-stock-a-buy-or-a.html  \nhttps://finance.yahoo.com/news/tesla-just-unveiled-mezcal-got-200000013.html  \nhttps://finance.yahoo.com/news/elon-musk-praises-boeings-leadership-182842424.html  \nhttps://seekingalpha.com/news/4390997-elon-musk-boeing-is-on-much-better-track-with-new-ceo  \nhttps://finance.yahoo.com/news/elon-musk-biggest-fans-turn-135830459.html  \nhttps://finance.yahoo.com/news/elon-musk-cost-cutter-working-090002891.html  \nhttps://finance.yahoo.com/news/live/stock-market-today-dow-ekes-out-gains-bitcoin-slumps-as-santa-claus-rally-takes-a-pause-175235354.html  \nhttps://finance.yahoo.com/news/live/stock-market-today-dow-sp-500-nasdaq-futures-fall-after-christmas-break-140313607.html",
  title: "Tesla Report Delivery Numbers Soon",
  pdfUrl:
    "https://d2gewc5xha837s.cloudfront.net/newsclocker/insight-pdf/tesla_report_delivery_numbers_soon_20241227215133.pdf",
  isRead: true,
  isStarred: false,
  isTrashed: true,
};

export const exampleSubscription: NewsSubscription = {
  id: "cm554j1vv000vkp6uatn2kcnz",
  name: "Tesla",
  userId: "user_2pthEoa2M0CuCs0pzdjInOTLwcl",
  keywords: ["Tesla", " Elon Musk", " Tesla stock", " Tesla FSD"],
  language: "en",
  country: "us",
  dateRange: "past_24_hours",
  active: true,
  frequency: "every_day",
  timeToSend: "13:06",
  timezone: "Asia/Hong_Kong",
  nextRunTime: new Date("2024-12-29T05:06:00"),
  newsSources: ["seekingalpha.com", "finance.yahoo.com"],
  newsPrompt:
    "1. **Identify Key Elements**: Focus on the provided news article related to Tesla, Elon Musk, Tesla stock, and Tesla FSD (Full Self-Driving).  \n2. **Evaluate Company Performance**: Analyze any mentions of Tesla's financial performance, including revenue, earnings, and growth metrics. Highlight any significant improvements or declines.  \n3. **Assess Industry Trends**: Examine the broader electric vehicle (EV) and autonomous driving industry trends. Identify any developments or shifts that could impact Tesla's position in the market.  \n4. **Gauge Market Sentiment**: Evaluate the tone and sentiment of the article, including public perception, investor confidence, and media coverage. Note any positive or negative sentiment shifts.  \n5. **Identify Buy Signals**: Based on the analysis, pinpoint specific buy signals such as positive earnings reports, favorable industry developments, or optimistic market sentiment.  \n6. **Highlight Risks**: Summarize any negative indicators or risks, such as regulatory challenges, competitive threats, or negative sentiment.  \n7. **Provide Actionable Insights**: Conclude with a clear summary of the findings, including a recommendation on whether the current indicators suggest a potential buying opportunity for Tesla stock.  \n8. **Step-by-Step Summary**: Present the analysis in a structured format, detailing the positive and negative indicators, and their potential impact on Tesla stock.  \n\n**Optimized Prompt**:  \nAnalyze the provided news article related to Tesla, Elon Musk, Tesla stock, and Tesla FSD. Evaluate Tesla's company performance, including financial metrics and growth indicators. Assess industry trends in the EV and autonomous driving sectors, noting any developments that could influence Tesla's market position. Gauge market sentiment by analyzing the tone of the article, public perception, and investor confidence. Identify specific buy signals such as positive earnings, favorable industry shifts, or optimistic sentiment. Highlight any risks or negative indicators, including regulatory challenges or competitive threats. Provide a structured summary of the analysis, detailing both positive and negative factors, and conclude with actionable insights on whether the current indicators suggest a potential buying opportunity for Tesla stock.",
  createdAt: new Date("2024-12-26T09:31:00.043000"),
  updatedAt: new Date("2024-12-29T05:05:36.844000"),
  status: "RUNNING",
};
