import { NewsSubscription } from "@prisma/client";

export const mockSubscriptions: NewsSubscription[] = [
  {
    id: "1",
    name: "AI Trend",
    userId: "user1",
    keywords: ["Artificial Intelligence", "Machine Learning"],
    language: "en",
    dateRange: "past_24_hours",
    active: true,
    frequency: "every_day",
    timeToSend: "09:00",
    timezone: "America/New_York",
    nextRunTime: new Date(Date.now() + 24 * 60 * 60 * 1000),
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "COMPLETED",
    newsSources: [],
  },
  {
    id: "2",
    userId: "user1",
    name: "Blockchain",
    keywords: ["Blockchain", "Cryptocurrency"],
    language: "en",
    dateRange: "past_week",
    active: false,
    frequency: "every_week",
    timeToSend: "02:00",
    nextRunTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    timezone: "America/New_York",
    createdAt: new Date(),
    updatedAt: new Date(),
    status: "COMPLETED",
    newsSources: [],
  },
];
